### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by marqh** [opengeospatial/netcdf-ld#29]
Within the standard, the term `broadcast` is used extensively.  This was initially adopted from the Python Numpy implementation, e.g.
https://numpy.org/devdocs/user/theory.broadcasting.html

I think the document assumes too much knowledge, and that this term should be defined, and it's use expanded on in the standard, with pictures and with external references.

The bald vocabulary explicitly defines two properties: `childBroadcast` and `parentBroadcast`
These are related to broadcasting, but are actually shape statements, or perhaps reshape statements.

I think that the use of `parent` and `child` imply too strong a hierarchy.  There isn't a hierarchy here, there is just a directional relationship: A has an array reference to B

I think that the shape aspect of the properties is the key,  broadcasting is the downstream use.   I think we should consider renaming these two properties

@adamml @jyucsiro

**Comment by marqh** [comment]
perhaps:
* `bald:sourceShape`
* `bald:targetShape`

**Comment by marqh** [comment]
perhaps:
* `bald:sourceReshape`
* `bald:targetReshape`

**Comment by marqh** [comment]
I wonder, given the complicated nature of netCDF dimensions and the desire on my part to promote clarity, whether it is worth a bit of information duplication here.  We are creating graphs from files, so having information in 2 places, as it is useful, rather than one and only one place, for enforced preservation of consistency, could be deemed a price worth paying for promoting clarity of intent and implementation.

Specifically, we could include a `bald:sourceShape` and a `bald:sourceReshape` statement on a `bald:Reference` entity, demonstrating the matching of number of dimensions and number of entities in each case.

This would also enable the `bald:sourceReshape` statement to be optional, as if reshape = shape then shape is sufficient.

E.g. if both are mandated:

```
this:deptht_deptht_bnds_ref a bald:Reference,
        bald:Subject ;
    bald:sourceReshape ( 4 1 ) ;
    bald:sourceShape ( 4 ) ;
    bald:target this:deptht_bnds ;
    bald:targetReshape ( 4 2 ) ;
    bald:targetShape ( 4 2 ) .
```

and if reshape == shape makes reshape unnecessary:

```
this:deptht_deptht_bnds_ref a bald:Reference,
        bald:Subject ;
    bald:sourceReshape ( 4 1 ) ;
    bald:sourceShape ( 4 ) ;
    bald:target this:deptht_bnds ;
    bald:targetShape ( 4 2 ) .
```

I think this looks clearer to me. 
I recognise the price that the `bald:sourceShape` is already stated in the source entity as `bald:shape`, and that this opens up the possibility for mismatch.
I am interested whether this may be worth the price,  to make the shape-to-reshape relations clearer and closer together.


@der @skwlilac   thoughts on this topic would be very welcome


for context, the graph would also include 2 entities representing the 2 nc variables that this relationship is between, in this case:

```
this:deptht a bald:Array,
        bald:Reference ;
    bald:array this:deptht ;
    bald:first_value 0.0 ;
    bald:last_value 1000.0 ;
    bald:references this:deptht_deptht_bnds_ref,
        this:deptht_deptht_ref ;
    bald:shape ( 4 ) ;
    CFTerms:bounds this:deptht_bnds ;
    CFTerms:positive "down" ;
    CFTerms:standard_name <http://vocab.nerc.ac.uk/standard_name/depth/> ;
    NetCDF:long_name "Vertical T levels" ;
    NetCDF:title "deptht" ;
    NetCDF:units "m" .

this:deptht_bnds a bald:Array ;
    bald:references this:deptht_bnds_deptht_ref ;
    bald:shape ( 4 2 ) .

```

**Comment by skwlilac** [comment]
Hello @marqh 

I'm not sure I have any well-formed thoughts on this. I'm just trying to get to grips with broadcasting. I think I understand it in principle, but it is also understanding how the axes of the variables/arrays line up (let alone understanding the subtle differences between shape and reshape).

IIUC from the referenced numpy docs, then the trailing dimension (ie. from the RH end of the array decl) need to be aligned in size (or 1) at corresponding positions from the RH end. I can also see that for the lower rank(?) array then effectively the dimension at the LH end expand out with '1' so that that accumulated LH end can be broadcast over the remaining dimensions and the results combined. What would really help (me) is a visual illustration of  this example from the numpy page

A | (4d array) | 8 x | 1 x | 6 x | 1
-- | -- | -- | -- | -- | --
B | (3d array) |   | 7 x | 1 x | 5
Result | (4d array) | 8 x | 7 x | 6 x | 5

Or something like it reduced to 3 and 2 dimensions rather than 4 and 3 so as to make it more easily visual.

Regarding this example from above:

```
this:deptht_deptht_bnds_ref a bald:Reference,
        bald:Subject ;
    bald:sourceReshape ( 4 1 ) ;
    bald:sourceShape ( 4 ) ;
    bald:target this:deptht_bnds ;
    bald:targetReshape ( 4 2 ) ;
    bald:targetShape ( 4 2 ) .
```

Firstly, am I right in understanding that:

1. the dimensional alignments are rooted at the LH (head) end of the list?
2. the source and target shapes reflect the shapes of the corresponding array/variables prior to broadcasting?
3. the reshapes as the shapes required (of both arrays - ie. they might both be reshaped) by the reference.

If so... I'm curious why the source reshape is (4 1) and not (4 2) so that reshaped source and target are then the same shape. Left as (4 1), if I understand things will require a further broadcast of the source array so as to match the target.

I'm also curious that in the context of numpy the broadcasting is implicit and driven calculations being done. In NetCDF we have mere referencing and its then not clear what the analog of the arithmetic operators is (BTW in numpy do the necessary broadcast shapes vary with operator). 

It also seems apparent that reshaping may be required at both ends of a reference. 

I am wondering whether the reshaping required is entirely given by the shapes at each end of the reference and doesn't infact need to be stated (though it may be a convenience to do so) - and that the source and target shapes should already be carried by the corresponding variables/arrays.

[Just finding my way and thinking out loud].

**Comment by ethanrd** [comment]
@marqh Not coming from the python world, the use of `broadcast` and `reshape` was not, on first read, at all clear to me so I definitely agree with your initial comment about needing to further define `broadcast` and such.

After reading a bit about numpy array broadcasting, I think I understand, to some degree, how you are using it to describe the relationship between netCDF data variables and associated `coordinate variable`s (and other variable references). However, I still find the terminology a bit odd. It feels more active (in terms of manipulating and reshaping arrays) rather than what I think of as a more passive mapping.

I’m not sure I’m explaining that very well. And it may be my rather new and limited understanding of numpy array broadcasting but I wanted to share these thoughts in case they are useful.

**Comment by adamml** [comment]
@marqh I tend to agree with @ethanrd here.

I think in our initial drafts we have almost certainly assumed too much knowledge, and too closely aligned our naming conventions with the Python community. I think some clarification for more general / all users is, as you rightly say, needed.

My preference from the suggestions so far would be the one you have at https://github.com/opengeospatial/netCDF-Classic-LD/issues/29#issuecomment-548704816

**Comment by der** [comment]
@marqh Using the terminology of `source` and `target` instead of `parent` and `child` does seem preferable since, as you say, there's no hierarchy involved.

Similarly, using the terminology of shape relationships is preferable to that of "broadcast". This meaning for "broadcast" is rather specific to Python and I agree with @ethanrd that it implies an active processing function whereas bald should be capturing the declarative relationships between the two variables.

@skwlilac the reason for the `reshape` mapping to `(4 1)` is that it is orienting the coordinate dimension as a vector within the same dimensional space as the target. The difference between the `sourceReshape` and the `targetShape` (i.e. the axes of length `1`) then tells you which dimensions to spread (or "broadcast") over. Thus the suggested approach is very much the same as the existing draft with a change of terminology.

There is a question of which is _source_ and which is _target_. From a declarative point of view I'd argue that a "natural" view of the relationship is that it goes from the measurement variable to the coordinate variables. The dimensions and coordinate variables standalone whereas the measurement variable depends on the coordinate variables for interpretation. Hence I would have expected the source to be the higher dimensionality measurement variable and the target to be the coordinate variable. However, I can see that if you think in terms of the processing with python/numpy, rather than the declarative relationship, then you are mapping and broadcasting the coordinates into the higher dimensional space. So from that point of view coordinate-variable-as-source makes sense. I'm happy to accept which ever direction makes most sense to likely users. Ultimately it's arbitrary and just has to be clear in the specification.

**Comment by der** [comment]
@marqh One further thought on this. Having tried some non-trivial examples manually there is indeed quite a lot of repetition of shape information. As you note there's a trade-off here on redundancy v.s. local clarity. When first looking at the issue I was in favour of prioritising local clarity but on reflection, after trying it out, I'm inclined towards not having the redundancy - so only have `bald:sourceReshape` and `bald:targetReshape`. However, it's a fine balance.

One ancillary question which might help tip the balance ...

Do you anticipate implementers being allowed to use blank nodes for the reference resources? The examples show URIs being created for these but the spec narrative doesn't (I don't think) spell this out. In some ways a bNode would be clearer since the Reference resource is really only there to express a structured relationship it's not something I would expect to be able to link to from outside the document graph or have multiple links inside the graph. Using bNodes your example (simplified) would look like:

```
this:deptht a bald:Array;
    NetCDF:long_name "Vertical T levels" ;
    NetCDF:title "deptht" ;       # other metadata omitted for clarity
    bald:shape ( 4 ) ;
    bald:references [
        bald:sourceReshape ( 4 1 ) ;
        bald:target this:deptht_bnds ;        
    ] .

this:deptht_bnds a bald:Array ;
    bald:shape ( 4 2 );
    bald:references [
        bald:targetReshape ( 4 1 );
        bald:target this:deptht ;
    ] .
```

With inlined bNodes the redundant expression of  source/target shapes would seem, well, more redundant.

**Comment by marqh** [comment]
'der

using blank nodes is a neat way to make this more compact and avoid the creation of extra resources that don't exist within the file.

i have been concerned about making up names for entities that are just reference definers and I had not considered making them blank nodes.

As you state, this make the `sourceShape` unnecessary.

I'll update your example slightly here, as I think I would expect a reference such as this example to only be defined one way: `deptht` -> `deptht_bnds`.

On this basis, I think that `targetShape` may still be useful, to directly compare to `targetReshape`, if it is required and to compare to `sourceReshape`, if required and `shape`. 

```
this:deptht a bald:Array;
    NetCDF:long_name "Vertical T levels" ;
    NetCDF:title "deptht" ;       # other metadata omitted for clarity
    bald:shape ( 4 ) ;
    bald:references [
        bald:sourceReshape ( 4 1 ) ;
        bald:target this:deptht_bnds ;        
        bald:targetShape (4 2) ;
    ] .

this:deptht_bnds a bald:Array ;
    bald:shape ( 4 2 );
    ] .
```

I think this is a really useful addition, I will investigate implementing this as an option.

**Comment by marqh** [comment]
> @marqh Not coming from the python world, the use of `broadcast` and `reshape` was not, on first read, at all clear to me so I definitely agree with your initial comment about needing to further define `broadcast` and such.
> 
> After reading a bit about numpy array broadcasting, I think I understand, to some degree, how you are using it to describe the relationship between netCDF data variables and associated `coordinate variable`s (and other variable references). However, I still find the terminology a bit odd. It feels more active (in terms of manipulating and reshaping arrays) rather than what I think of as a more passive mapping.
> 
> I’m not sure I’m explaining that very well. And it may be my rather new and limited understanding of numpy array broadcasting but I wanted to share these thoughts in case they are useful.

Hi @ethanrd 

this is really useful, thank you

I think that these relations should have a static sense about them.  I think that broadcasting as a term should drift into the background; it's useful, but it's not the key here, it is an implementation of the result, I think.  Additionally, perhaps not the only one.

Defining the relationships between data variables and coordinate variables are the key deliverable here.  Extending this to other, multi-dimensional, variable to variable referencing is important as well.

I have used `reshape` as a term which I take to mean a shape with the same overall number of elements, but extra dimensions of size 1 added, to match the dimensionality and ordering of another shape.
This enables indexing operations, which are a broad and vital class of operation, to be supported across linked variables.

I wonder if we could explore some terms that might help to capture this?  I also wonder whether the definition of the term is the most important thing, as naming things well is one of the classic problems.
So:

* shape
  * an ordered list of integers defining the dimensionality and extent of a multi-dimensional array
* ??shape
  * a new shape, defined with respect to a shape, with extra dimensions added of size 1
    * number of elements is conserved: the product of the values of the new shape shall be the same as the product of the values of the original shape 
    * no re-ordering: the order of extensive elements in the new shape shall not differ from the order of extensive elements in the original shape
* ??shape
  * Reshape
  * RefShape
  * MapShape
  * ... ... ...


thoughts on the key content of this, the text for the definitions of terms and the choice of names are all greatly appreciated

thank you

**Comment by der** [comment]
@marqh 

Happy with the modified example and the suggestion to retain `targetShape`.

[I only had the links both ways because they both seemed to be present in your earlier example. Which I took to be that `deptht_bnds` references `deptht` as a dimension, and `deptht` references `deptht_bnds` via e.g. a CF `bounds` attribute. However, that's all orthogonal to the point of this issue.]

**Comment by marqh** [comment]
![multi_array](https://user-images.githubusercontent.com/1557321/69577296-fdd83380-0fc5-11ea-811c-564cd16bfa51.png)


![multi_array_to_cube](https://user-images.githubusercontent.com/1557321/69577312-029ce780-0fc6-11ea-8c90-8ec4538e9849.png)

**Comment by marqh** [comment]
as a user i want to index a data array to obtain a value, and, using the same index operation, obtain the relevant value for each of the referenced data arrays.

e.g. i would like 1 air temperature value, together with the appropriate value for latitude, longitude and height

**Comment by marqh** [comment]
* bald:sourceRefShape
* bald:targetShape
* bald:targetRefShape

seem to capture the static nature of these reference relations quite well

**Comment by jyucsiro** [comment]
I think sourceRefShape and targetRefShape addresses the passive/active discussion (*RefShape appears to me to use more passive language).

the blank node style looks neat also.

**Comment by adamml** [comment]
Bump.

In working on #62 I noticed that there is a placeholder in Section 4 to give a definition of Broadcast (4.7) but no text as yet.

**Comment by jyucsiro** [comment]
Text exists for broadcast. Close this issue then?

**Comment by marqh** [comment]
yes, this should be handled by the recent work, including #76 and #81

outstanding is the definition in Section 4
