### ISSUE TITLE
Handling UNLIMITED dimensions

### ISSUE THREAD

**Issue by der** [opengeospatial/netcdf-ld#31]
Apologies if this is already covered, I couldn't find a mention of it in the current document or open issues.

NetCDF Classic allows up to one dimension to be of UNLIMITED length; NetCDF-4 allows multiple such dimensions.

The current draft represents the shape of a variable as a list of integers, the lengths of the corresponding dimensions. So how should a variable with an UNLIMITED dimension be represented?

I imagine possibilities might include:

1. Define a constant `bald:unlimited` to represent this case.

2. Use an otherwise illegal integer (e.g. -1).

3. Use `INF^^xsd:float`. There is no `INF` in the value space for xsd:decimal (and thus xsd:integer) but there is in `xsd:float` and `xsd:double`. 

Non of these feel particularly clean though arguably (1) most directly signals the intention.

/cc @marqh @skwlilac

**Comment by marqh** [comment]
Hi @der 

I think that this is a case that we can bypass this as an implementation detail.

the `unlimited` is not provided instead of a size, it is provided in addition to a size.

this is a hangover from the legacy encoding where one and only one dimension could be added to when providing further data to an existing file:
http://www-c4.ucsd.edu/netCDF/netcdf-guide/guide_8.html

it's preserved for the HDF5 encoding in netCDF4 but its essentially a legacy

the key point is that this is about how a file may be manipulated in the future, it is not about the semantics of the file contents at the time it is parsed.

each dimension is defined by one and only one integer: the size

whether a dimension is flagged as unlimited or not is only of interest if an operation want to append data to an existing file.

for all of our archive use cases, this is not allowed, a file must be PUT wholly

for all cases that I can think of for indexing file contents, this information does not seem relevant.

thus I prpose that unlimited is left as an implementation detail and not included in the parsed metadata summary. I'm not in favour of adding functionality to support this concept. 

given the nuance of this, I suggest we keep this ticket open and try to summarise the perspective within the specification, to make it clear the unlimited will never be represented in a metadata summary graph. 

that also give opportunities for challenge and discussion on my perspective

cheers

**Comment by ethanrd** [comment]
I agree with @marqh 's summarization and conclusion.

My only point of clarification is around the netCDF-4 use of `unlimited`. In netCDF-4 there can be multiple `unlimited` dimensions. The `unlimited` dimensions are, like in netCDF-3, the only dimensions along which data can be appended without rewriting the data file.

**Comment by der** [comment]
I can accept this answer but for the record let me summarize the counter arguments.

1. While it's true that any netcdf file will have an actual number of entries for the unlimited dimension(s) this is not apparent in the metadata as represented in CDL. For example, in https://www.unidata.ucar.edu/software/netcdf/examples/sresa1b_ncar_ccsm3-example.cdl the actual size of the time dimension is not stated in machine readable terms other than by having to scan the time coordinate dimension variable and count the number of entries. That scan would be quick in this case but not necessarily in others.

2. For the MetOffice use cases it would be convenient to be able to represent the schema for a set of data files not just a single concrete file. Taking the CCSM3 example. That file is one time step from a set of runs and the data can be provided as a whole run or as sequence of time steps. It may be convenient to be able to use bald to describe the shape/schema of the data (variables, shape of the geographic grid, shape of the pressure level dimension) which is common to the different ways of packaging the results by time step.

Neither of these are clinchers. If the use cases for bald are entirely limited to describing single, closed files then I agree if can be omitted.

**Comment by marqh** [comment]
>     1. While it's true that any netcdf file will have an actual number of entries for the unlimited dimension(s) this is not apparent in the metadata as represented in CDL. For example, in https://www.unidata.ucar.edu/software/netcdf/examples/sresa1b_ncar_ccsm3-example.cdl the actual size of the time dimension is not stated in machine readable terms other than by having to scan the time coordinate dimension variable and count the number of entries. That scan would be quick in this case but not necessarily in others.

Hi @der 

this is the case in the CDL, but this is not so much of a problem, as we will expect to parse metadata from binary netCDF files.  The size of the dimension is encoded in the binary format and can be obtained directly, there is no need to try and parse the CDL text, the current dimension size is directly accessible via the netCDF API


Item 2 is more nuanced and interesting, I think we should continue to investigate this theme, as it may have far wider implications than just 'unlimited' 

many thanks
mark
