### ISSUE TITLE
bald:isPrefixedBy reference value

### ISSUE THREAD

**Issue by simonoakesepimorphics** [opengeospatial/netcdf-ld#87]
In #85 it was clarified that the [BALD vocabulary](https://raw.githubusercontent.com/opengeospatial/NamingAuthority/master/incubation/binary-array-ld/binary-array-ld.ttl) would be used to interpret variable to variable references for resource-valued properties, in particular the `bald:references` relationship.

The vocab also specifies that bald:isPrefixedBy is a resource-valued property, and therefore its values should be interpreted as possible variable references. In conformance class [A.2.1](http://docs.opengeospatial.org/DRAFTS/19-002.html#_requirement_1_2) (and in many places throughout the document), the `bald__isPrefixedBy` attribute is "prefix_list", which is the name of a variable, however the `bald:isPrefixedBy` property in the output graph is evaluated as a raw string rather than as a variable URI. This is a slightly obscure case since the `prefix_list` variable is excluded from the output graph.

As I see it there are a few options:
* Do not treat "prefix_list" as a variable reference since the variable is excluded from the output (current spec).
* Do treat "prefix_list" as a variable reference since it satisfies all of the criteria in [6.5.8](http://docs.opengeospatial.org/DRAFTS/19-002.html#_attribute_variable_references).
* Exclude the `bald:isPrefixedBy` relationship from the output graph because it is acting as an annotation for the linked data converter and does not necessarily contain meaningful information about the binary array itself.

@marqh

**Comment by marqh** [comment]
@simonoakesepimorphics 

thank for exploring this

I think that the BALD vocabulary is valid in stating that `bald:isPrefixedBy` does define a reference. however it doesn't seem to add value to include this reference within the output metadata graph, as it is providing mechanics

as such i tend to prefer

* Exclude the bald:isPrefixedBy relationship from the output graph because it is acting as an annotation for the linked data converter and does not necessarily contain meaningful information about the binary array itself.

does this count as a special case that is worth explicit statement as part of the normative definition as an exception?

**Comment by simonoakesepimorphics** [comment]
I think it should be stated in the spec in the same way as the exclusion of the in-line prefix map ([link](http://docs.opengeospatial.org/DRAFTS/19-002.html#_prefix_declaration_in_file)) and something to that effect should be added to the normative section [A2](http://docs.opengeospatial.org/DRAFTS/19-002.html#_requirement_1_2). As a result several of the examples throughout the document which include `bald:isPrefixedBy` would need to be updated.
